# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbeea334d9dc4c6f3142c7d124cc2c2b3bce4b3e06934b6c385fe56687d8ef7162718056fe0c46f6ce7b7f0bc783cba5c48712c6bfc5b8a4699e702b0c53bfdc

test:
  secret_key_base: 5b24a0d5a3b7b72b0ef1d6619ee2a0097f40aaf7662801dc2fa6e5684f584d5fca099b894af4fe0a5fbab8bdcb9c09c9abc5086c7a3f64641fcde7d945c798b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
